services:
  db:
    image: postgres:15-alpine
    container_name: tasks_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - private_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: tasks_app
    environment:
      APP_PORT: ${APP_PORT}
      API_KEY: ${API_KEY}
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      DB_EXEC_TIMEOUT_SEC: ${DB_EXEC_TIMEOUT_SEC}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private_net

volumes:
  pgdata:

networks:
  private_net:
    name: tasks_private_net
    driver: bridge
